/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhointerface;

import java.awt.Color;

/**
 *
 * @author CLEBER
 */
public class CadastrarAlunos extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarAlunos
     */
    public CadastrarAlunos() {
        initComponents();
                Color cinza = new Color(80, 80, 80);
        getContentPane().setBackground(cinza);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CPFTextField = new javax.swing.JTextField();
        RegisterUserButton = new javax.swing.JButton();
        BirthDateTextField = new javax.swing.JTextField();
        AgeTextField = new javax.swing.JTextField();
        EnderecoLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        GenderFemaleCheckBox = new javax.swing.JCheckBox();
        CPFLabel = new javax.swing.JLabel();
        GenderMaleCheckBox = new javax.swing.JCheckBox();
        BirthdateLabel = new javax.swing.JLabel();
        escrita1 = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        logoUfu = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        EnderecoTextField = new javax.swing.JTextField();
        NameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        CPFTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPFTextFieldActionPerformed(evt);
            }
        });

        RegisterUserButton.setText("CADASTRAR ALUNO");
        RegisterUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterUserButtonActionPerformed(evt);
            }
        });

        EnderecoLabel.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        EnderecoLabel.setForeground(new java.awt.Color(255, 255, 255));
        EnderecoLabel.setText("ENDERECO:");

        GenderLabel.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        GenderLabel.setForeground(new java.awt.Color(255, 255, 255));
        GenderLabel.setText("GÊNERO:");

        GenderFemaleCheckBox.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        GenderFemaleCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        GenderFemaleCheckBox.setText("Feminino");
        GenderFemaleCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderFemaleCheckBoxActionPerformed(evt);
            }
        });

        CPFLabel.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        CPFLabel.setForeground(new java.awt.Color(255, 255, 255));
        CPFLabel.setText("CPF:");

        GenderMaleCheckBox.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        GenderMaleCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        GenderMaleCheckBox.setText("Masculino");
        GenderMaleCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderMaleCheckBoxActionPerformed(evt);
            }
        });

        BirthdateLabel.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        BirthdateLabel.setForeground(new java.awt.Color(255, 255, 255));
        BirthdateLabel.setText("DATA DE NASCIMENTO:");

        escrita1.setFont(new java.awt.Font("Lato Black", 1, 18)); // NOI18N
        escrita1.setForeground(new java.awt.Color(255, 255, 255));
        escrita1.setText("CADASTRO DE ALUNOS");

        NameLabel.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameLabel.setText("NOME COMPLETO:");

        logoUfu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/LOGO UFUACADEMI.png"))); // NOI18N

        AgeLabel.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        AgeLabel.setForeground(new java.awt.Color(255, 255, 255));
        AgeLabel.setText("IDADE:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AgeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BirthdateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BirthDateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CPFLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CPFTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NameTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EnderecoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EnderecoTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GenderLabel)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GenderMaleCheckBox)
                            .addComponent(GenderFemaleCheckBox))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(RegisterUserButton)
                .addGap(132, 132, 132))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoUfu, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(escrita1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoUfu, javax.swing.GroupLayout.PREFERRED_SIZE, 91, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escrita1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel)
                    .addComponent(AgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthdateLabel)
                    .addComponent(BirthDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPFLabel)
                    .addComponent(CPFTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnderecoLabel)
                    .addComponent(EnderecoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLabel)
                    .addComponent(GenderFemaleCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GenderMaleCheckBox)
                .addGap(18, 18, 18)
                .addComponent(RegisterUserButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CPFTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPFTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPFTextFieldActionPerformed

    private void RegisterUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterUserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterUserButtonActionPerformed

    private void GenderFemaleCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderFemaleCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderFemaleCheckBoxActionPerformed

    private void GenderMaleCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderMaleCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderMaleCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JTextField AgeTextField;
    private javax.swing.JTextField BirthDateTextField;
    private javax.swing.JLabel BirthdateLabel;
    private javax.swing.JLabel CPFLabel;
    private javax.swing.JTextField CPFTextField;
    private javax.swing.JLabel EnderecoLabel;
    private javax.swing.JTextField EnderecoTextField;
    private javax.swing.JCheckBox GenderFemaleCheckBox;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JCheckBox GenderMaleCheckBox;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JButton RegisterUserButton;
    private javax.swing.JLabel escrita1;
    private javax.swing.JLabel logoUfu;
    // End of variables declaration//GEN-END:variables
}
