/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacetrabalho;

/**
 *
 * @author CLEBER
 */
import java.awt.Color;

public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form Interface1
     */
    public TelaInicial() {
        initComponents();
        setLocationRelativeTo(null);
        Color azulUfu = new Color(53,51,117);
        getContentPane().setBackground(azulUfu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTextField3 = new javax.swing.JTextField();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuBar7 = new javax.swing.JMenuBar();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenuBar8 = new javax.swing.JMenuBar();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenuBar9 = new javax.swing.JMenuBar();
        jMenu17 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar10 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenuBar11 = new javax.swing.JMenuBar();
        jMenu20 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jMenuBar12 = new javax.swing.JMenuBar();
        jMenu22 = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();
        jMenuBar13 = new javax.swing.JMenuBar();
        jMenu24 = new javax.swing.JMenu();
        jMenu25 = new javax.swing.JMenu();
        jMenuBar14 = new javax.swing.JMenuBar();
        jMenu26 = new javax.swing.JMenu();
        jMenu27 = new javax.swing.JMenu();
        jMenuBar15 = new javax.swing.JMenuBar();
        jMenu28 = new javax.swing.JMenu();
        jMenu29 = new javax.swing.JMenu();
        jMenuBar16 = new javax.swing.JMenuBar();
        jMenu30 = new javax.swing.JMenu();
        jMenu31 = new javax.swing.JMenu();
        jMenuBar17 = new javax.swing.JMenuBar();
        jMenu32 = new javax.swing.JMenu();
        jMenu33 = new javax.swing.JMenu();
        jMenuBar18 = new javax.swing.JMenuBar();
        jMenu34 = new javax.swing.JMenu();
        jMenu35 = new javax.swing.JMenu();
        jMenuBar19 = new javax.swing.JMenuBar();
        jMenu36 = new javax.swing.JMenu();
        jMenu37 = new javax.swing.JMenu();
        jMenuBar20 = new javax.swing.JMenuBar();
        jMenu38 = new javax.swing.JMenu();
        jMenu39 = new javax.swing.JMenu();
        jMenuBar21 = new javax.swing.JMenuBar();
        jMenu40 = new javax.swing.JMenu();
        jMenu41 = new javax.swing.JMenu();
        jMenuBar22 = new javax.swing.JMenuBar();
        jMenu42 = new javax.swing.JMenu();
        jMenu43 = new javax.swing.JMenu();
        jMenuBar23 = new javax.swing.JMenuBar();
        jMenu44 = new javax.swing.JMenu();
        jMenu45 = new javax.swing.JMenu();
        jMenuBar24 = new javax.swing.JMenuBar();
        jMenu46 = new javax.swing.JMenu();
        jMenu47 = new javax.swing.JMenu();
        jMenuBar25 = new javax.swing.JMenuBar();
        jMenu48 = new javax.swing.JMenu();
        jMenu49 = new javax.swing.JMenu();
        jMenuBar26 = new javax.swing.JMenuBar();
        jMenu50 = new javax.swing.JMenu();
        jMenu51 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuBar27 = new javax.swing.JMenuBar();
        jMenu52 = new javax.swing.JMenu();
        jMenu53 = new javax.swing.JMenu();
        jMenuBar28 = new javax.swing.JMenuBar();
        jMenu54 = new javax.swing.JMenu();
        jMenu55 = new javax.swing.JMenu();
        jMenuBar29 = new javax.swing.JMenuBar();
        jMenu56 = new javax.swing.JMenu();
        jMenu57 = new javax.swing.JMenu();
        jMenuBar30 = new javax.swing.JMenuBar();
        jMenu58 = new javax.swing.JMenu();
        jMenu59 = new javax.swing.JMenu();
        jMenuBar31 = new javax.swing.JMenuBar();
        jMenu60 = new javax.swing.JMenu();
        jMenu61 = new javax.swing.JMenu();
        jMenuBar32 = new javax.swing.JMenuBar();
        jMenu62 = new javax.swing.JMenu();
        jMenu63 = new javax.swing.JMenu();
        jMenuBar33 = new javax.swing.JMenuBar();
        jMenu64 = new javax.swing.JMenu();
        jMenu65 = new javax.swing.JMenu();
        jMenuBar34 = new javax.swing.JMenuBar();
        jMenu66 = new javax.swing.JMenu();
        jMenu67 = new javax.swing.JMenu();
        jMenuBar35 = new javax.swing.JMenuBar();
        jMenu68 = new javax.swing.JMenu();
        jMenu69 = new javax.swing.JMenu();
        jMenuBar36 = new javax.swing.JMenuBar();
        jMenu70 = new javax.swing.JMenu();
        jMenu71 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar4.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("File");
        jMenuBar5.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar5.add(jMenu9);

        jMenu10.setText("jMenu10");

        jMenu11.setText("File");
        jMenuBar6.add(jMenu11);

        jMenu12.setText("Edit");
        jMenuBar6.add(jMenu12);

        jMenu13.setText("File");
        jMenuBar7.add(jMenu13);

        jMenu14.setText("Edit");
        jMenuBar7.add(jMenu14);

        jMenu15.setText("File");
        jMenuBar8.add(jMenu15);

        jMenu16.setText("Edit");
        jMenuBar8.add(jMenu16);

        jMenu17.setText("File");
        jMenuBar9.add(jMenu17);

        jMenu18.setText("Edit");
        jMenuBar9.add(jMenu18);

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar10.add(jMenu3);

        jMenu19.setText("Edit");
        jMenuBar10.add(jMenu19);

        jMenu20.setText("File");
        jMenuBar11.add(jMenu20);

        jMenu21.setText("Edit");
        jMenuBar11.add(jMenu21);

        jMenu22.setText("File");
        jMenuBar12.add(jMenu22);

        jMenu23.setText("Edit");
        jMenuBar12.add(jMenu23);

        jMenu24.setText("File");
        jMenuBar13.add(jMenu24);

        jMenu25.setText("Edit");
        jMenuBar13.add(jMenu25);

        jMenu26.setText("File");
        jMenuBar14.add(jMenu26);

        jMenu27.setText("Edit");
        jMenuBar14.add(jMenu27);

        jMenu28.setText("File");
        jMenuBar15.add(jMenu28);

        jMenu29.setText("Edit");
        jMenuBar15.add(jMenu29);

        jMenu30.setText("File");
        jMenuBar16.add(jMenu30);

        jMenu31.setText("Edit");
        jMenuBar16.add(jMenu31);

        jMenu32.setText("File");
        jMenuBar17.add(jMenu32);

        jMenu33.setText("Edit");
        jMenuBar17.add(jMenu33);

        jMenu34.setText("File");
        jMenuBar18.add(jMenu34);

        jMenu35.setText("Edit");
        jMenuBar18.add(jMenu35);

        jMenu36.setText("File");
        jMenuBar19.add(jMenu36);

        jMenu37.setText("Edit");
        jMenuBar19.add(jMenu37);

        jMenu38.setText("File");
        jMenuBar20.add(jMenu38);

        jMenu39.setText("Edit");
        jMenuBar20.add(jMenu39);

        jMenu40.setText("File");
        jMenuBar21.add(jMenu40);

        jMenu41.setText("Edit");
        jMenuBar21.add(jMenu41);

        jMenu42.setText("File");
        jMenuBar22.add(jMenu42);

        jMenu43.setText("Edit");
        jMenuBar22.add(jMenu43);

        jMenu44.setText("File");
        jMenuBar23.add(jMenu44);

        jMenu45.setText("Edit");
        jMenuBar23.add(jMenu45);

        jMenu46.setText("File");
        jMenuBar24.add(jMenu46);

        jMenu47.setText("Edit");
        jMenuBar24.add(jMenu47);

        jMenu48.setText("File");
        jMenuBar25.add(jMenu48);

        jMenu49.setText("Edit");
        jMenuBar25.add(jMenu49);

        jMenu50.setText("File");
        jMenuBar26.add(jMenu50);

        jMenu51.setText("Edit");
        jMenuBar26.add(jMenu51);

        jMenuItem2.setText("jMenuItem2");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenu52.setText("File");
        jMenuBar27.add(jMenu52);

        jMenu53.setText("Edit");
        jMenuBar27.add(jMenu53);

        jMenu54.setText("File");
        jMenuBar28.add(jMenu54);

        jMenu55.setText("Edit");
        jMenuBar28.add(jMenu55);

        jMenu56.setText("File");
        jMenuBar29.add(jMenu56);

        jMenu57.setText("Edit");
        jMenuBar29.add(jMenu57);

        jMenu58.setText("File");
        jMenuBar30.add(jMenu58);

        jMenu59.setText("Edit");
        jMenuBar30.add(jMenu59);

        jMenu60.setText("File");
        jMenuBar31.add(jMenu60);

        jMenu61.setText("Edit");
        jMenuBar31.add(jMenu61);

        jMenu62.setText("File");
        jMenuBar32.add(jMenu62);

        jMenu63.setText("Edit");
        jMenuBar32.add(jMenu63);

        jMenu64.setText("File");
        jMenuBar33.add(jMenu64);

        jMenu65.setText("Edit");
        jMenuBar33.add(jMenu65);

        jMenu66.setText("File");
        jMenuBar34.add(jMenu66);

        jMenu67.setText("Edit");
        jMenuBar34.add(jMenu67);

        jMenu68.setText("File");
        jMenuBar35.add(jMenu68);

        jMenu69.setText("Edit");
        jMenuBar35.add(jMenu69);

        jMenu70.setText("File");
        jMenuBar36.add(jMenu70);

        jMenu71.setText("Edit");
        jMenuBar36.add(jMenu71);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(82, 82, 82))
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu31;
    private javax.swing.JMenu jMenu32;
    private javax.swing.JMenu jMenu33;
    private javax.swing.JMenu jMenu34;
    private javax.swing.JMenu jMenu35;
    private javax.swing.JMenu jMenu36;
    private javax.swing.JMenu jMenu37;
    private javax.swing.JMenu jMenu38;
    private javax.swing.JMenu jMenu39;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu40;
    private javax.swing.JMenu jMenu41;
    private javax.swing.JMenu jMenu42;
    private javax.swing.JMenu jMenu43;
    private javax.swing.JMenu jMenu44;
    private javax.swing.JMenu jMenu45;
    private javax.swing.JMenu jMenu46;
    private javax.swing.JMenu jMenu47;
    private javax.swing.JMenu jMenu48;
    private javax.swing.JMenu jMenu49;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu50;
    private javax.swing.JMenu jMenu51;
    private javax.swing.JMenu jMenu52;
    private javax.swing.JMenu jMenu53;
    private javax.swing.JMenu jMenu54;
    private javax.swing.JMenu jMenu55;
    private javax.swing.JMenu jMenu56;
    private javax.swing.JMenu jMenu57;
    private javax.swing.JMenu jMenu58;
    private javax.swing.JMenu jMenu59;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu60;
    private javax.swing.JMenu jMenu61;
    private javax.swing.JMenu jMenu62;
    private javax.swing.JMenu jMenu63;
    private javax.swing.JMenu jMenu64;
    private javax.swing.JMenu jMenu65;
    private javax.swing.JMenu jMenu66;
    private javax.swing.JMenu jMenu67;
    private javax.swing.JMenu jMenu68;
    private javax.swing.JMenu jMenu69;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu70;
    private javax.swing.JMenu jMenu71;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar10;
    private javax.swing.JMenuBar jMenuBar11;
    private javax.swing.JMenuBar jMenuBar12;
    private javax.swing.JMenuBar jMenuBar13;
    private javax.swing.JMenuBar jMenuBar14;
    private javax.swing.JMenuBar jMenuBar15;
    private javax.swing.JMenuBar jMenuBar16;
    private javax.swing.JMenuBar jMenuBar17;
    private javax.swing.JMenuBar jMenuBar18;
    private javax.swing.JMenuBar jMenuBar19;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar20;
    private javax.swing.JMenuBar jMenuBar21;
    private javax.swing.JMenuBar jMenuBar22;
    private javax.swing.JMenuBar jMenuBar23;
    private javax.swing.JMenuBar jMenuBar24;
    private javax.swing.JMenuBar jMenuBar25;
    private javax.swing.JMenuBar jMenuBar26;
    private javax.swing.JMenuBar jMenuBar27;
    private javax.swing.JMenuBar jMenuBar28;
    private javax.swing.JMenuBar jMenuBar29;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar30;
    private javax.swing.JMenuBar jMenuBar31;
    private javax.swing.JMenuBar jMenuBar32;
    private javax.swing.JMenuBar jMenuBar33;
    private javax.swing.JMenuBar jMenuBar34;
    private javax.swing.JMenuBar jMenuBar35;
    private javax.swing.JMenuBar jMenuBar36;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuBar jMenuBar7;
    private javax.swing.JMenuBar jMenuBar8;
    private javax.swing.JMenuBar jMenuBar9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
